add parse level error
charmbracelet/log pull request #83
Opened 2023-10-31 06:17 UTC by dezren39

2023-10-31 22:28 UTC, aymanbagabas requested changes
Thank you @dezren39 for this work, a few comments below

2023-10-31 22:28 UTC, aymanbagabas commented on level.go
> +
```suggestion
// ErrInvalidLevel is an error returned when parsing an invalid level string.
var ErrInvalidLevel = errors.New("invalid level")
```

2023-10-31 22:28 UTC, aymanbagabas commented on level.go
> +		return InfoLevel, parseLevelError(level)
```suggestion
		return InfoLevel, fmt.Errorf("%w: %q", ErrInvalidLevel, level)
```

2023-10-31 22:28 UTC, aymanbagabas commented on level_test.go
> +		result parseLevelResult
```suggestion
		result Level
		error error
```

2023-10-31 22:28 UTC, aymanbagabas commented on level_test.go
> +
```suggestion
```

2023-11-06 16:42 UTC, aymanbagabas requested changes

2023-11-06 16:42 UTC, aymanbagabas commented on level.go
> +		return defaultLogger.GetLevel(), fmt.Errorf("%w: %q", ErrInvalidLevel, level)
```suggestion
		return 0, fmt.Errorf("%w: %q", ErrInvalidLevel, level)
```

2023-11-06 22:26 UTC, dezren39 commented on level.go
> +		return 0, fmt.Errorf("%w: %q", ErrInvalidLevel, level)
```suggestion
		return InfoLevel, fmt.Errorf("%w: %q", ErrInvalidLevel, level)
```

2023-11-07 13:28 UTC, dezren39 commented on level.go
> +		return InfoLevel, fmt.Errorf("%w: %q", ErrInvalidLevel, level)
```suggestion
		return 0, fmt.Errorf("%w: %q", ErrInvalidLevel, level)
```

2023-11-07 13:52 UTC, aymanbagabas approved these changes

2023-11-07 13:52 UTC, merged